services:
  ts-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend
    restart: unless-stopped
    init: true
    ports:
      - "10000:10000"
    env_file: ./.env
    environment:
    - MONGODB_URI=mongodb://mongo:27017/panameconsultingDb
    - EMAIL_USER=${EMAIL_USER}
    - EMAIL_PASS=${EMAIL_PASS}
    - JWT_SECRET=${JWT_SECRET}
    - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    - PORT=10000
    - NODE_ENV=production
    networks:
      - appnet