services:
  ts-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend
    restart: unless-stopped
    init: true
    ports:
      - "10000:10000" # Expose NestJS default port
    env_file: ./.env  # Uncomment if .env file exists

    environment:
    - MONGODB_URI
    - EMAIL_USER
    - EMAIL_PASS
    - JWT_SECRET
    - PORT

    networks:
      - appnet
    # Add depends_on here if you add external services below

# If you discover external dependencies (e.g. MongoDB, Redis), add them below:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

# Uncomment and use if you add persistent services above
volumes:
 mongo-data:
   driver: local
